tasks:
  - init: git remote set-url origin git@github.com:pavithra-nagarajan/pavithra-nagarajan-StudentEnrollment.git && sed "s/\r$//" commit-command.sh | bash
vscode:
 extensions:
   - revaturePro.revature-labs